services:
  app:
    build: .
    container_name: cgp-laravel-app
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: cgp-postgres
    restart: always
    environment:
      POSTGRES_DB: cgp
      POSTGRES_USER: cgp
      POSTGRES_PASSWORD: cgp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/sql/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres_data:
